#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py migrate_pipeline_settings --sync-preferences --init-only
python manage.py migrate_pipeline_settings
python manage.py runserver 0.0.0.0:8000
