# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_agent_corpus_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentactionresult",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="agentconfiguration",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
