# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0012_update_chat_field_constraint_for_threads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="corpusmoderator",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="messagevote",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="userreputation",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
