# Generated by Django 5.2.11 on 2026-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0016_update_checkconstraint_check_to_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="compacted_before_message_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID of the last message that was folded into compaction_summary.  Messages with id <= this value are excluded from LLM context (but kept in the DB).  Stored as a plain integer (not a ForeignKey) so the id__gt filter remains valid even if the cutoff message is deleted.",
                null=True,
            ),
        ),
    ]
