# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0050_add_structural_set_structural_flag_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="annotationlabel",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="embedding",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="labelset",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="structuralannotationset",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
