# Generated by Django 4.2.24 on 2026-01-10 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0051_alter_annotation_backend_lock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="content_modalities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                help_text="Content modalities present in this annotation: TEXT, IMAGE, etc.",
                size=None,
            ),
        ),
    ]
