# Generated by Django 4.2.24 on 2026-01-12 19:49

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0056_alter_structuralannotationset_content_hash"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="annotation",
            name="idx_ann_content_modalities_gin",
        ),
        migrations.AddField(
            model_name="embedding",
            name="vector_4096",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=4096, null=True
            ),
        ),
    ]
