# Generated by Django 4.2.24 on 2026-01-12 19:52

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0057_add_vector_4096_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="vector_1024",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
