# Generated by Django 4.2.24 on 2026-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0058_add_vector_1024_and_4096_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="embedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False)),
                fields=("embedder_path", "document"),
                name="unique_embedding_per_document_embedder",
            ),
        ),
        migrations.AddConstraint(
            model_name="embedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("annotation__isnull", False)),
                fields=("embedder_path", "annotation"),
                name="unique_embedding_per_annotation_embedder",
            ),
        ),
        migrations.AddConstraint(
            model_name="embedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("note__isnull", False)),
                fields=("embedder_path", "note"),
                name="unique_embedding_per_note_embedder",
            ),
        ),
        migrations.AddConstraint(
            model_name="embedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation__isnull", False)),
                fields=("embedder_path", "conversation"),
                name="unique_embedding_per_conversation_embedder",
            ),
        ),
        migrations.AddConstraint(
            model_name="embedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message__isnull", False)),
                fields=("embedder_path", "message"),
                name="unique_embedding_per_message_embedder",
            ),
        ),
    ]
