# Generated by Django 4.2.24 on 2026-01-16 16:49

import functools

from django.db import migrations, models
import opencontractserver.shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0059_add_embedding_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="image_content_file",
            field=models.FileField(
                blank=True,
                help_text="JSON file containing extracted image data for IMAGE modality annotations",
                null=True,
                upload_to=functools.partial(
                    opencontractserver.shared.utils.calc_oc_file_path,
                    sub_folder="annotation_images",
                ),
            ),
        ),
    ]
