# Generated by Django 4.2.24 on 2026-01-27 04:37

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0060_add_annotation_image_content_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="vector_2048",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=2048, null=True
            ),
        ),
    ]
