# Generated by Django 5.2.11 on 2026-03-08 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0063_add_hnsw_indexes_and_search_vector"),
        ("corpuses", "0046_change_disabled_on_clone_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="corpus_action",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this annotation was created by a corpus action agent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_annotations",
                to="corpuses.corpusaction",
            ),
        ),
    ]
