# Generated by Django 5.2.11 on 2026-03-08 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0020_update_checkconstraint_check_to_condition"),
        ("annotations", "0064_add_corpus_action_fk_to_annotation"),
        ("corpuses", "0046_change_disabled_on_clone_default_false"),
        ("documents", "0035_add_enabled_components_to_pipeline_settings"),
        ("extracts", "0028_rename_placeholder_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["corpus_action"], name="annotations_corpus__78e0c3_idx"
            ),
        ),
    ]
