# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_add_profile_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimport",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
