# Generated by Django 4.2.24 on 2026-01-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_create_installation_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dismissed_getting_started",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has dismissed the Getting Started guide on the Discover page",
                verbose_name="Dismissed Getting Started",
            ),
        ),
    ]
