# Generated by Django 5.2.11 on 2026-02-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worker_uploads", "0003_hash_token_keys"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="corpusaccesstoken",
            new_name="worker_uplo_worker__316c0e_idx",
            old_name="worker_uplo_worker__d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="corpusaccesstoken",
            new_name="worker_uplo_is_acti_73f6ba_idx",
            old_name="worker_uplo_is_acti_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="workeraccount",
            new_name="worker_uplo_name_7f93db_idx",
            old_name="worker_uplo_name_8c3b2d_idx",
        ),
        migrations.RenameIndex(
            model_name="workeraccount",
            new_name="worker_uplo_is_acti_f924a9_idx",
            old_name="worker_uplo_is_acti_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="workerdocumentupload",
            new_name="worker_uplo_status_a9c908_idx",
            old_name="worker_uplo_status_j1k2l3_idx",
        ),
        migrations.RenameIndex(
            model_name="workerdocumentupload",
            new_name="worker_uplo_corpus__ecd8cb_idx",
            old_name="worker_uplo_corpus__m4n5o6_idx",
        ),
        migrations.RenameIndex(
            model_name="workerdocumentupload",
            new_name="worker_uplo_corpus__c75c7b_idx",
            old_name="worker_uplo_corpus__p7q8r9_idx",
        ),
    ]
