# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0025_merge_20251013_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="datacell",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="extract",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="fieldset",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
