# Generated by Django 5.2.11 on 2026-02-28 19:56
# Index names in 0027 used hand-crafted hash suffixes; correct to
# Django's auto-generated values.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0027_add_datacell_document_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="datacell",
            new_name="extracts_da_documen_2ce84c_idx",
            old_name="extracts_da_documen_b8c4f5_idx",
        ),
        migrations.RenameIndex(
            model_name="datacell",
            new_name="extracts_da_documen_a86c47_idx",
            old_name="extracts_da_documen_7f2e3a_idx",
        ),
    ]
