# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_userfeedback_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
