# Generated by Django 4.2.24 on 2026-01-06 04:07
# Modified to handle already-dropped tables from migration 0033

from django.db import migrations


class Migration(migrations.Migration):
    """
    Clean up Django's migration state for CorpusQuery models that were
    already dropped via raw SQL in migration 0033_remove_corpusquery.

    This migration uses state_operations to update Django's internal state
    without touching the database (tables were already dropped).
    """

    dependencies = [
        ("corpuses", "0035_seed_default_categories"),
    ]

    operations = [
        # These are state-only operations - tables were already dropped in 0033
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="CorpusQueryGroupObjectPermission",
                ),
                migrations.DeleteModel(
                    name="CorpusQueryUserObjectPermission",
                ),
                migrations.DeleteModel(
                    name="CorpusQuery",
                ),
            ],
            database_operations=[],  # No DB changes needed - already done
        ),
    ]
