# Generated by Django 5.2.11 on 2026-02-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_update_checkconstraint_check_to_condition"),
        ("corpuses", "0042_update_checkconstraint_check_to_condition"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="corpus",
            new_name="corpuses_co_creator_c32eb3_idx",
            old_name="corpuses_co_creator_0e8c8f_idx",
        ),
        migrations.AlterField(
            model_name="corpus",
            name="preferred_embedder",
            field=models.CharField(
                blank=True,
                help_text="Fully qualified Python path to the embedder class to use for this corpus. Auto-populated from DEFAULT_EMBEDDER at creation if not set. Immutable after documents are added (use re-embed to change).",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="corpusaction",
            name="agent_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional agent configuration for persona/tool defaults. Not required for agent actions — task_instructions alone is sufficient.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corpus_actions",
                to="agents.agentconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="corpusaction",
            name="pre_authorized_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tools pre-authorized to run without approval. If empty, uses agent_config.available_tools or trigger-appropriate defaults.",
            ),
        ),
    ]
