# Generated by Django 5.2.11 on 2026-02-28 19:56
# Index name in 0037 used a hand-crafted hash suffix; correct to
# Django's auto-generated value.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0043_alter_corpus_preferred_embedder_and_more"),
        ("corpuses", "0043_backfill_corpus_slugs"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="corpus",
            new_name="corpuses_co_creator_c32eb3_idx",
            old_name="corpuses_co_creator_0e8c8f_idx",
        ),
    ]
