# Generated by Django 5.2.11 on 2026-03-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0045_corpusactiontemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusactiontemplate",
            name="disabled_on_clone",
            field=models.BooleanField(
                default=False,
                help_text="If True, cloned actions start disabled (user must opt-in).",
            ),
        ),
    ]
