# Generated by Django 5.2.11 on 2026-03-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0045_corpusactiontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusaction",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template this action was cloned from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cloned_actions",
                to="corpuses.corpusactiontemplate",
            ),
        ),
    ]
