# Generated by Django 5.2.11 on 2026-03-09 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0047_corpus_license_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="license_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to the full license text. Required when license is 'CUSTOM', optional for standard CC licenses.",
                max_length=512,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
    ]
