# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0026_add_structural_annotation_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="documentanalysisrow",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="documentpath",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="documentrelationship",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
