# Generated by Django 4.2.24 on 2026-01-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0027_alter_document_backend_lock_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentrelationship",
            index=models.Index(
                fields=["corpus"], name="documents_d_corpus__581d7b_idx"
            ),
        ),
    ]
