# Generated by Django 4.2.24 on 2026-02-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0031_add_pipeline_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinesettings",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
