# Generated by Django 4.2.24 on 2026-02-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0032_add_index_to_pipeline_settings_modified"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pipelinesettings",
            constraint=models.CheckConstraint(
                check=models.Q(("pk", 1)), name="pipeline_settings_singleton_pk"
            ),
        ),
    ]
