# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0033_add_singleton_constraint_to_pipeline_settings"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pipelinesettings",
            name="pipeline_settings_singleton_pk",
        ),
        migrations.AddConstraint(
            model_name="pipelinesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", 1)),
                name="pipeline_settings_singleton_pk",
            ),
        ),
    ]
