# Generated by Django 4.2.24 on 2025-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0017_merge_20251013_0333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="analyzer",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="gremlinengine",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
