# Generated by Django 5.2.11

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0019_alter_analyzer_is_public_alter_gremlinengine_is_public"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="analyzer",
            name="one_field_null_constraint",
        ),
        migrations.AddConstraint(
            model_name="analyzer",
            constraint=models.CheckConstraint(
                condition=(
                    django.db.models.Q(
                        host_gremlin__isnull=True, task_name__isnull=False
                    )
                    | django.db.models.Q(
                        host_gremlin__isnull=False, task_name__isnull=True
                    )
                ),
                name="one_field_null_constraint",
            ),
        ),
    ]
